### ISSUE TITLE
united the font family and size

### ISSUE THREAD

**Issue by hshahwan** [FACG5/unicornz#125]
Hi again,
make sure that you use the same font family and font size, you add it in app.css.

####  title : use lora 
```Size: 30px
Weight: Bold
Line-height: 40px
Tracking: +10 
````

#### Body Copy :Lato
```Size: 11px
Weight: Regular
Line-height: 15px
Tracking: +10

**Comment by maxgerber** [comment]
@hshahwan why are you labelling this issue, as well as issues #118, #123, #124, #125, #130, #131, and #132 as "wontfix"? 😕

**Comment by maxgerber** [comment]
Haha oh! That's better. I thought you were assigning issues that you didn't want to fix!

**Comment by hshahwan** [comment]
Yes, I will change it, don't worry.
