### ISSUE TITLE
Showing error messages that correspond to the number of incorrectly inputed fields

### ISSUE THREAD

**Issue by yasminhillis** [FACG5/unicornz#160]
On the `sign up` form, if the user has inputted more than one field incorrectly, your error messages do not inform him/her with **all** the errors. 

See here what happens when I try to input three fields incorrectly: 
- I tried to input two mismatching passwords.
- I intentionally answered the mathematical quiz incorrectly
- And I did not tick `I'm not a robot` checkbox

I got  **ONLY** one error message about the mismatching passwords: 

<img width="869" alt="screen shot 2018-12-09 at 11 03 28 pm" src="https://user-images.githubusercontent.com/30685524/49702952-b10a1a00-fc07-11e8-83ee-947b22eee206.png">

After matching the two passwords, but keeping the two incorrectly inputed values, I got only **one error message** about not ticking the checkbox (notice the incorrect answer in the background): 

**Side note**: The error message needs more styling 

<img width="896" alt="screen shot 2018-12-09 at 11 14 28 pm" src="https://user-images.githubusercontent.com/30685524/49702999-38f02400-fc08-11e8-962e-1d905a603f32.png">

And even after ticking the checkbox, the same error message persists: 

<img width="895" alt="screen shot 2018-12-09 at 11 17 01 pm" src="https://user-images.githubusercontent.com/30685524/49703043-b320a880-fc08-11e8-9428-1686de5987a6.png">

I'd also recommend giving informative messages on what **exactly** went wrong when there is feedback. See this issue for reference: https://github.com/FACG5/unicornz/issues/154#issue-389052438

**Comment by donia98** [comment]
Oh! that is because we check one by one so the message will lead you to correct a specific field after that if you click submit you will have the next input validation and so on, I think this way is correct what do you think ?!
